### ISSUE TITLE
Issue with sign

### ISSUE THREAD

**Issue by StavZ** [5zig/The-5zig-Mod#23]
When i place and edit sign minecraft crashes
![Screenshot_17](https://user-images.githubusercontent.com/36641973/63079912-55d3b880-bf48-11e9-8be6-478c8024d299.png)

In log file 
[10:30:28] [5zig Netty Bootstrap/ERROR]: An Exception occurred while connecting to 5zig.net:28499
java.net.ConnectException: Connection timed out: no further information: 5zig.net/194.169.211.46:28499
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_51]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_51]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:208) ~[NioSocketChannel.class:4.0.23.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:287) ~[AbstractNioChannel$AbstractNioUnsafe.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) ~[NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[NioEventLoop.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[10:30:28] [5zig Netty Bootstrap/INFO]: Reconnecting in 79 seconds...

**Comment by S10MC2015** [comment]
1) That has nothing to do with a crash.
2) 5zig is now out of development
3) Use 5zig Reborn is you want a still updating 5zig
